# Site
name: Caltech Admissions Blog
title: "Caltech Admissions Blog"
description: "Explore life at Caltech!"
logo: 'assets/images/logo.png'
favicon: 'favicon.ico'
url: "caltechadmissions.blog" 
include: ["_pages"] 
permalink: /:title/

# Authors
authors:
  authors:
  annabel: 
    name: Annabel 
    display_name: Annabel Reyna 
    avatar: "assets/profilepics/agomez.png" 
    description: "Hello, my name is Annabel Reyna Gomez! I am a sophomore from the San Francisco Bay Area 
    (home of the Silicon Valley) pursuing a major in Mechanical Engineering. On campus, I am a member of 
    Ruddock House, Club Latino, Women Mentoring Women, a Caltech Y Rise Tutor, and an Admissions Ambassador. 
    Off campus, I intern at NASA’s Jet Propulsion Laboratory (JPL) using machine-learning to research and predict
    ionospheric irregularities. During my free time, I enjoy 3D printing, watching movies with
    my friends, and reading personal-development books."
  andrew:
    name: Andrew
    display_name: I Think I Chan    
    avatar: 'assets/profilepics/amchan.png'
    description: "I'm a senior from Denver, Colorado (the land of Patagonia jackets and 
    unpredictable weather). At Caltech I'm on the fencing team foil squad captain and SAAC 
    representative, a member of chemistry club and ultimate frisbee team, and the Fleming House 
    food committee representative. In my free time, I like to hike, write poetry, shoot photos, 
    and explore LA for trendy food."
  sunny: 
    name: sunny
    display_name: Just a Sunny Day 
    avatar: 'assets/profilepics/ccui.png'
    description: "I'm from Vancouver, BC where it rains over 200 days a year. At Caltech, 
    I serve on the excomm of the Caltech Y and Society of Women Engineers and play piano 
    with the chamber music program. When I'm not doing sets and lab work, I enjoy hiking, 
    shopping, cooking, drawing, and scouring the internet for items to add to her never-ending 
    bucket list."
  tessa: 
    name: tessa
    display_name: Tessa 
    avatar: 'assets/profilepics/ttweet.png'
    description: "I grew up in the Seattle area and moved to Southern California to attend 
    Pitzer College in Claremont (and for the sunshine!) I graduated with a B.A. in Anthropology, 
    inspired by my love of museums and material culture and studied abroad in the Amazon region 
    of Brazil. After interning at The Getty Foundation, I worked in museum education at Huntington 
    Library (just down the street from Caltech). Even though I come from a humanities background, 
    I am a Techer at heart who always wants to hear about what students are working on in the lab 
    so I can live vicariously through them."
  rashi: 
    name: rashi 
    display_name: Rashi Jeeda  
    avatar: 'assets/profilepics/rjeeda.png'
    description: "Hi! I’m Rashi, a California girl who grew up in Pasadena, practically next door 
    to campus. I’m a junior majoring in Bioengineering and would typically be spending my days at 
    Caltech messing with the genome of E. coli in lab. On campus, I do synthetic bio research, 
    have dabbled in a bit of electrical engineering with the Racing team, am part of the Bollywood 
    dance team Caltech Dhamaka, and like to spend time exploring the area with friends!"
  andy:
    name: andy 
    display_name: LOL Andy 
    avatar: 'assets/profilepics/arothstein.png'
    description: "Life Of a Lloydie - Andy. Hello! I'm a senior physics major with a minor in aerospace 
    engineering from from Bethesda, Maryland. I'm a member of Lloyd House (and was the president 
    last year), help out as a dean's tutor, wait house dinners, and swim. Outside of the more 
    structured activities, I'm always on the hunt for the best KBBQ restaurant or really any 
    ayce place."
  sydney: 
    name: sydney 
    display_name: Sydney Richardson 
    avatar: 'assets/profilepics/srichard.png'
    description: "Hello! I’m Sydney, a Junior from the Sacramento area studying Mechanical Engineering. 
    I play on Caltech’s volleyball team and I‘m a member of Fleming house. I participate in clubs 
    such as the Caltech Latino Association, the Society of Women Engineers, and FSAE (we build a racecar)! 
    Alongside meeting and talking to new people, I love art, the ocean, pupusas 
    (the national dish of El Salvador), and of course STEM!"
  vmechem:
    name: vmechem
    display_name: Vanessa Mechem
    avatar: 'assets/profilepics/vmechem.png'
    description: "Hi! I am Vanessa, a Junior Chem major and pre-med student. I am originally from Shanghai, 
    China but I've been living in sunny Southern California for the past 7 years. I am the Vice President of 
    Page House, a Health Advocate, and a member of the Clemons lab. I love dancing, singing (poorly), 
    goofing off with my friends, playing poker, and watching the same shows on Netflix for the 15th time."
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - kramdown
  
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-caltechadmissions-blog

# Instagram 
instagram_user_id: 17841400885573472
instagram_client_id: 998967617301035
instagram_access_token: IGQVJYa1VvbV9QWGlmNWZAoOFozdGctbmhBdzhSVHpvMWk0aTlsZAGFyc1F2ZAzQ2bk5nNnZAzVW02aWpxMjg5Y01MaDJTMVF3T1ZANUnhwZAnhraW1IODVUaF9XUENfTFJJNjFQd1NSNXU5eDlXR0MzcjN3WlNyNkw1RXZAXVmcw
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
